wandb_version: 1

aug_strength:
  value: 0
batch_size:
  value: 15
deterministic:
  value: true
fold_index:
  value: 0
folds:
  value: 5
gpus:
  value: 1
label_var:
  value: is_tumor
lr:
  value: 0.0003620947610971102
max_epochs:
  value: 20
num_workers:
  value: 10
out_dir:
  value: /mnt/disks/disk_use/blca/ml_results/models
paths_df:
  value: /mnt/disks/disk_use/blca/path_dataframes/ff_stain_norm_mag_20_pix_512.pkl
prefix:
  value: ff_stainnorm_20x_512px_
seed:
  value: 182
slide_var:
  value: slide_id
split_ids:
  value: /mnt/disks/disk_use/blca/ml_results/train_val_test_splits/TvN
tiles_per_slide:
  value: 433
